apiKey: 8843240933:AAESwgiO89CQydhMdXcV23LN4nnc0BSfm6U
country: GB

notification:
  ntfy:
    url: https://ntfy.sh
    topic: bts-tickets-2026

global:
  regions:
    - GBLO
  eventSimilarity: 0.9
  numTickets: 2
  maxTicketPrice: 125

tickets:
  - event: BTS
