apiKey: 83d6ec0c-54bb-4da3-b2a1-f3cb47b984f1
country: GB

notification:
  ntfy:
    url: https://ntfy.sh
    topic: bts-tickets-2026

global:
  regions:
    - GBLO # London only
  maxTicketPrice: 110
  numTickets: 2

tickets:
  - event: BTS
